import LegalLayout from './LegalLayout'

export default function PrivacyPolicyContent() {
  return (
    <LegalLayout
      title="Privacy Policy"
      subtitle="This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service."
      lastUpdated="May 26, 2026"
    >

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words whose initial letters are capitalized have meanings defined under the following conditions.
        The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><span className="definition-term">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><span className="definition-term">Affiliate</span> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><span className="definition-term">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Digital Marketing Firm, 67A, Giri Rd, Srinivasapuram, Balaganapathy Nagar, Thanjavur, Tamil Nadu 613009.</li>
        <li><span className="definition-term">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><span className="definition-term">Country</span> refers to: Tamil Nadu, India</li>
        <li><span className="definition-term">Device</span> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
        <li><span className="definition-term">Personal Data</span> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
        <li><span className="definition-term">Service</span> refers to the Website.</li>
        <li><span className="definition-term">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
        <li><span className="definition-term">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><span className="definition-term">Website</span> refers to ARA Discover Marketing, accessible from <a href="https://discovermarketing.co/" target="_blank" rel="noreferrer">https://discovermarketing.co/</a></li>
        <li><span className="definition-term">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>

      <h3>Personal Data</h3>
      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information
        that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <h3>Usage Data</h3>
      <p>
        Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's
        Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit,
        the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may collect certain information automatically, including,
        but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile
        device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>

      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.
        Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and
        analyze Our Service. The technologies We use may include:
      </p>
      <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email.</li>
      </ul>
      <p>
        Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with
        Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or
        through Your browser/device settings.
      </p>
      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul>
        <li><strong>Necessary / Essential Cookies</strong> — Session Cookies administered by Us. These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — Persistent Cookies administered by Us. These Cookies identify if users have accepted the use of cookies on the Website.</li>
        <li><strong>Functionality Cookies</strong> — Persistent Cookies administered by Us. These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
      </ul>

      <h2>Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
        <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract.</li>
        <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
        <li>To provide You with news, special offers, and general information about other goods, services and events.</li>
        <li>To manage Your requests: To attend and manage Your requests to Us.</li>
        <li>For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer.</li>
        <li>For other purposes: data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service.</li>
      </ul>

      <p>We may share Your Personal Data in the following situations:</p>
      <ul>
        <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service.</li>
        <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with any merger, sale of Company assets, financing, or acquisition.</li>
        <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
        <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
        <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
      </ul>

      <h2>Retention of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
        We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes,
        and enforce our legal agreements and policies.
      </p>
      <p>
        Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data.
        We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:
      </p>
      <ul>
        <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
        <li><strong>Support tickets and correspondence:</strong> up to 24 months from the date of ticket closure.</li>
        <li><strong>Chat transcripts:</strong> up to 24 months for quality assurance and staff training purposes.</li>
        <li><strong>Website analytics data:</strong> up to 24 months from the date of collection.</li>
        <li><strong>Server logs:</strong> up to 24 months for security monitoring and troubleshooting purposes.</li>
      </ul>
      <p>
        When retention periods expire, We securely delete or anonymize Personal Data. Residual copies may remain in encrypted backups
        for a limited period and are not restored except where necessary for security, disaster recovery, or legal compliance.
      </p>

      <h2>Transfer of Your Personal Data</h2>
      <p>
        Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the
        parties involved in the processing are located. This means that this information may be transferred to and maintained on
        computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws
        may differ from those of Your jurisdiction.
      </p>
      <p>
        Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate
        safeguards. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance
        with this Privacy Policy.
      </p>

      <h2>Delete Your Personal Data</h2>
      <p>
        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        Our Service may give You the ability to delete certain information about You from within the Service.
      </p>
      <p>
        You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings
        section. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.
        Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
      </p>

      <h2>Disclosure of Your Personal Data</h2>
      <h3>Business Transactions</h3>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide
        notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
      </p>
      <h3>Law Enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in
        response to valid requests by public authorities (e.g. a court or a government agency).
      </p>
      <h3>Other Legal Requirements</h3>
      <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h2>Security of Your Personal Data</h2>
      <p>
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet,
        or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your
        Personal Data, We cannot guarantee its absolute security.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information
        from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with
        Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16
        without verification of parental consent, We take steps to remove that information from Our servers.
      </p>

      <h2>Links to Other Websites</h2>
      <p>
        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will
        be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party
        sites or services.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy
        on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective,
        and update the "Last updated" date at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective
        when they are posted on this page.
      </p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>By email: <a href="mailto:aradiscovermarketing@gmail.com">aradiscovermarketing@gmail.com</a></li>
        <li>By phone: <a href="tel:+918110025254">+91 81100 25254</a></li>
      </ul>

    </LegalLayout>
  )
}
