import { FileBarChart, Headphones, Activity, Shield, TrendingUp, DollarSign, Award, ArrowRight, CheckCircle2 } from 'lucide-react'

const promises = [
  { icon: FileBarChart, title: 'Monthly Google Ads Performance Reports',     desc: 'Transparent monthly reports covering impressions, clicks, conversions, cost-per-lead, and ROAS for complete campaign visibility.',               color: '#2563eb' },
  { icon: Headphones,   title: 'Dedicated PPC Campaign Manager',             desc: 'A personal PPC manager assigned to your account with direct communication, proactive updates, and priority campaign support.',                    color: '#7c3aed' },
  { icon: Activity,     title: 'Real-Time Conversion & Lead Tracking',       desc: 'Full Google Ads and Analytics conversion tracking setup to measure every lead, call, and sale generated by your campaigns in real time.',         color: '#0891b2' },
  { icon: Shield,       title: 'ROI-Focused Ad Optimization',                desc: 'Every campaign decision is driven by ROI data — from bid adjustments to ad copy testing — ensuring your budget works as hard as possible.',        color: '#059669' },
  { icon: TrendingUp,   title: 'Smart Budget & Bid Management',              desc: 'AI-assisted bid management and smart budget allocation across campaigns to maximize conversions and minimize wasted spend consistently.',          color: '#dc2626' },
  { icon: DollarSign,   title: 'Transparent Reporting & Campaign Insights',  desc: 'No hidden fees, no jargon — clear campaign insights with actionable recommendations delivered every month to keep you fully informed.',           color: '#d97706' },
]

export default function SEMAssurance() {
  return (
    <section className="py-24 overflow-hidden"
      style={{ background: 'linear-gradient(160deg, #f8fbff 0%, #eff6ff 55%, #f0f9ff 100%)' }}>

      {/* Dot grid */}
      <div className="absolute inset-0 pointer-events-none"
        style={{ backgroundImage: 'radial-gradient(rgba(37,99,235,0.07) 1.5px, transparent 1.5px)', backgroundSize: '32px 32px' }} />

      {/* Orbs */}
      <div className="absolute top-0 right-0 w-[450px] h-[450px] rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(147,197,253,0.40) 0%, transparent 70%)' }} />
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(196,219,254,0.40) 0%, transparent 70%)' }} />

      <div className="relative max-w-[1200px] mx-auto px-7">

        {/* ── Header ── */}
        <div className="flex flex-col lg:flex-row gap-10 items-end mb-14 reveal">
          <div className="flex-1">
            <span className="inline-flex items-center gap-2 px-3.5 py-1.5 bg-white/80 text-blue-600
              border border-blue-200 rounded-full text-[11px] font-bold uppercase tracking-widest mb-5 shadow-sm">
              <Award size={11} /> Our Assurance
            </span>
            <h2 className="text-[clamp(26px,3.5vw,46px)] font-bold text-slate-900 leading-[1.1] tracking-tight">
              Our Assurance to{' '}
              <span className="text-gradient-blue">Every Client</span>
            </h2>
          </div>
          <div className="lg:max-w-[400px]">
            <p className="text-[15px] text-slate-600 leading-[1.85]">
              Businesses seeking reliable Google Pay advertisements in Thanjavur services trust us for transparent campaign management and consistent lead generation.
            </p>
          </div>
        </div>

        {/* ── Main layout: feature panel left + 2×3 grid right ── */}
        <div className="reveal flex flex-col lg:flex-row gap-6">

          {/* Left: light blue feature panel */}
          <div className="lg:w-[300px] flex-shrink-0">
            <div className="h-full rounded-3xl p-7 border border-blue-200 relative overflow-hidden"
              style={{
                background: 'linear-gradient(160deg, #dbeafe 0%, #bfdbfe 60%, #c7d2fe 100%)',
                boxShadow: '0 16px 50px rgba(37,99,235,0.14)',
              }}>

              {/* Decorative rings */}
              <div className="absolute -bottom-8 -right-8 w-44 h-44 rounded-full border-[2px] border-blue-400/20 pointer-events-none" />
              <div className="absolute -bottom-4 -right-4 w-24 h-24 rounded-full border border-blue-400/25 pointer-events-none" />

              {/* Dot grid overlay */}
              <div className="absolute inset-0 pointer-events-none"
                style={{ backgroundImage: 'radial-gradient(rgba(37,99,235,0.12) 1.5px, transparent 1.5px)', backgroundSize: '24px 24px' }} />

              <div className="relative">
                <div className="w-14 h-14 rounded-2xl flex items-center justify-center mb-6 text-white"
                  style={{ background: 'linear-gradient(135deg,#2563eb,#6366f1)', boxShadow: '0 6px 20px rgba(37,99,235,0.30)' }}>
                  <Award size={24} />
                </div>

                <h3 className="text-[18px] font-bold text-slate-900 leading-snug mb-4">
                  6 Core Commitments to Your Google Ads Success
                </h3>
                <p className="text-[13px] text-slate-600 leading-[1.8] mb-6">
                  Trusted among the top search engine marketing agencies in Thanjavur, every client receives a dedicated commitment from our team — from transparent reporting to AI-powered strategy. We don't just run ads, we grow your business.
                </p>

                {/* 3 micro highlights */}
                <div className="space-y-2.5 mb-7">
                  {['Transparent campaign management', 'Consistent lead generation', 'Dedicated support & reporting'].map(t => (
                    <div key={t} className="flex items-center gap-2">
                      <CheckCircle2 size={13} className="text-blue-600 flex-shrink-0" />
                      <span className="text-[12px] text-slate-700 font-medium">{t}</span>
                    </div>
                  ))}
                </div>

                <a href="#contact"
                  className="btn-glow inline-flex items-center gap-2 px-6 py-3 rounded-full text-[13px]
                    font-bold text-white transition-all duration-300 hover:opacity-90 hover:-translate-y-0.5"
                  style={{ background: 'linear-gradient(135deg,#2563eb,#6366f1)', boxShadow: '0 6px 24px rgba(37,99,235,0.30)' }}>
                  Start Your PPC Campaign Today <ArrowRight size={14} />
                </a>
              </div>
            </div>
          </div>

          {/* Right: 2×3 promise card grid */}
          <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-4">
            {promises.map(({ icon: Icon, title, desc, color }) => (
              <div key={title}
                className="group bg-white flex flex-col gap-3 p-5 rounded-2xl border border-slate-100
                  hover:-translate-y-0.5 hover:shadow-xl transition-all duration-300"
                style={{ boxShadow: '0 4px 18px rgba(37,99,235,0.06)' }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = color + '35' }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = '#f1f5f9' }}>

                {/* Top mini bar */}
                <div className="h-0.5 w-0 rounded-full group-hover:w-8 transition-all duration-300"
                  style={{ background: color }} />

                <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0
                  transition-all duration-300 group-hover:scale-110 group-hover:shadow-lg"
                  style={{ background: color + '14', border: `1.5px solid ${color}28` }}>
                  <Icon size={18} style={{ color }} />
                </div>
                <div>
                  <h3 className="text-[13.5px] font-bold text-slate-900 mb-1.5 leading-snug">{title}</h3>
                  <p className="text-[12.5px] text-slate-500 leading-[1.75]">{desc}</p>
                </div>
              </div>
            ))}
          </div>

        </div>
      </div>
    </section>
  )
}
